services:
  app:
    build: ./infra/php
    volumes:
      - ./:/data

  web:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
